name: Dependency Check Scan

on:
  push:
    branches:
      # - main
      - security-automation-additions
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      # - main
      - security-automation-additions
  workflow_dispatch:
    

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew
      #   working-directory: android

      # - name: Build Gradle project
      #   run: ./gradlew build
      #   working-directory: android

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: "fhircore"
          path: "."
          format: 'XML'
          out: 'reports'
        

      - name: Upload Dependency Check report in XML format
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report.xml
